SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `FOREST` ;
CREATE SCHEMA IF NOT EXISTS `FOREST` ;
USE `FOREST` ;

-- -----------------------------------------------------
-- Table `FOREST`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`CATEGORY` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `TAGS` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `SQL_CATEGORY_ID_INDEX` (`ID` ASC) );


-- -----------------------------------------------------
-- Table `FOREST`.`PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`PERSON` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`PERSON` (
  `ID` INT NOT NULL ,
  `FIRSTNAME` VARCHAR(50) NOT NULL ,
  `LASTNAME` VARCHAR(100) NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  `ADDRESS` VARCHAR(45) NOT NULL ,
  `CITY` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(100) NULL DEFAULT NULL ,
  `DTYPE` VARCHAR(31) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX (`EMAIL` ASC) ,
  UNIQUE INDEX `SQL_PERSON_EMAIL_INDEX` (`EMAIL` ASC) ,
  UNIQUE INDEX `SQL_PERSON_ID_INDEX` (`ID` ASC) );


-- -----------------------------------------------------
-- Table `FOREST`.`GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`GROUPS` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`GROUPS` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(50) NOT NULL ,
  `DESCRIPTION` VARCHAR(300) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) );


-- -----------------------------------------------------
-- Table `FOREST`.`PERSON_GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`PERSON_GROUPS` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`PERSON_GROUPS` (
  `GROUPS_ID` INT NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  INDEX `SQL_PERSONGROUPS_EMAIL_INDEX` (`EMAIL` ASC) ,
  INDEX `SQL_PERSONGROUPS_ID_INDEX` (`GROUPS_ID` ASC) ,
  CONSTRAINT `FK_PERSON_GROUPS_PERSON`
    FOREIGN KEY (`EMAIL` )
    REFERENCES `FOREST`.`PERSON` (`EMAIL` ),
  CONSTRAINT `FK_PERSON_GROUPS_GROUPS`
    FOREIGN KEY (`GROUPS_ID` )
    REFERENCES `FOREST`.`GROUPS` (`ID` ));


-- -----------------------------------------------------
-- Table `FOREST`.`ORDER_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`ORDER_STATUS` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`ORDER_STATUS` (
  `ID` INT NOT NULL ,
  `STATUS` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `SQL_ORDERSTATUS_ID_INDEX` (`ID` ASC) );


-- -----------------------------------------------------
-- Table `FOREST`.`CUSTOMER_ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`CUSTOMER_ORDER` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`CUSTOMER_ORDER` (
  `ID` INT NOT NULL ,
  `AMOUNT` FLOAT(52) NOT NULL ,
  `DATE_CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `CUSTOMER_ID` INT NOT NULL ,
  `STATUS_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SQL_ORDER_STATUS_ID_INDEX` (`STATUS_ID` ASC) ,
  INDEX `SQL_ORDER_CUSTOMER_ID_INDEX` (`CUSTOMER_ID` ASC) ,
  UNIQUE INDEX `SQL_ORDER_ID_INDEX` (`ID` ASC) ,
  CONSTRAINT `FK_CUSTOMER_ORDER_ORDER_STATUS1`
    FOREIGN KEY (`STATUS_ID` )
    REFERENCES `FOREST`.`ORDER_STATUS` (`ID` ),
  CONSTRAINT `FK_CUSTOMER_ORDER_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID` )
    REFERENCES `FOREST`.`PERSON` (`ID` ));


-- -----------------------------------------------------
-- Table `FOREST`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`PRODUCT` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`PRODUCT` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `PRICE` DECIMAL(10,2) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NOT NULL ,
  `IMG` VARCHAR(45) NULL DEFAULT NULL ,
  `CATEGORY_ID` INT NOT NULL ,
  `IMG_SRC` BLOB(1073741823) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `SQL_PRODUCT_ID_INDEX` (`ID` ASC) ,
  INDEX `FK_PRODUCT_CATEGORY` (`CATEGORY_ID` ASC) ,
  CONSTRAINT `FK_PRODUCT_CATEGORY`
    FOREIGN KEY (`CATEGORY_ID` )
    REFERENCES `FOREST`.`CATEGORY` (`ID` ));


-- -----------------------------------------------------
-- Table `FOREST`.`ORDER_DETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FOREST`.`ORDER_DETAIL` ;

CREATE  TABLE IF NOT EXISTS `FOREST`.`ORDER_DETAIL` (
  `ORDER_ID` INT NOT NULL ,
  `PRODUCT_ID` INT NOT NULL ,
  `QTY` INT NOT NULL ,
  PRIMARY KEY (`ORDER_ID`, `PRODUCT_ID`) ,
  UNIQUE INDEX `SQL_ORDER_DETAIL_INDEX` (`ORDER_ID` ASC, `PRODUCT_ID` ASC) ,
  INDEX `SQL_ORDER_PRODUCT_ID_INDEX` (`PRODUCT_ID` ASC) ,
  INDEX `SQL_ORDER_DETAIL_ID_INDEX` (`ORDER_ID` ASC) ,
  CONSTRAINT `FK_ORDER_DETAIL_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID` )
    REFERENCES `FOREST`.`PRODUCT` (`ID` ),
  CONSTRAINT `FK_ORDER_DETAIL_ORDER`
    FOREIGN KEY (`ORDER_ID` )
    REFERENCES `FOREST`.`CUSTOMER_ORDER` (`ID` ));



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
